// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

type User struct {
	ID   int32   `json:"id"`
	Name *string `json:"name"`
}

type Video struct {
	ID     int32   `json:"id"`
	Title  *string `json:"title"`
	Url    *string `json:"url"`
	Author *int    `json:"author"`
}
